export enum EAlgorithm {
  IRREGULAR_TRIANGLES = "IRREGULAR_TRIANGLES",
  INVERSE_SQUARE_DISTANCE = "INVERSE_SQUARE_DISTANCE",
  WEIGHTED_AVERAGE_BY_ORIENTATION = "WEIGHTED_AVERAGE_BY_ORIENTATION",
}
